import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
   return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: GridView.count(
        primary: false,
        padding: const EdgeInsets.all(20.0),
        crossAxisSpacing: 10.0,
        crossAxisCount: 2,
        children: <Widget>[
          Image.asset('icons/flags/png/de.png', package: 'country_icons'),
          Image.asset('icons/flags/png/gb.png', package: 'country_icons'),
          Image.asset('icons/flags/png/fr.png', package: 'country_icons'),
          Image.asset('icons/flags/png/es.png', package: 'country_icons'),
          Image.asset('icons/flags/png/it.png', package: 'country_icons'),
          Image.asset('icons/flags/png/eu.png', package: 'country_icons'),

          Image.asset('icons/flags/png/2.5x/de.png', package: 'country_icons'),
          Image.asset('icons/flags/png/2.5x/gb.png', package: 'country_icons'),
          Image.asset('icons/flags/png/2.5x/fr.png', package: 'country_icons'),
          Image.asset('icons/flags/png/2.5x/es.png', package: 'country_icons'),
          Image.asset('icons/flags/png/2.5x/it.png', package: 'country_icons'),
          Image.asset('icons/flags/png/2.5x/eu.png', package: 'country_icons'),

          SvgPicture.asset('icons/flags/svg/ad.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ae.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/af.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ag.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ai.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/al.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/am.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/an.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ao.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/aq.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ar.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/as.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/at.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/au.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/aw.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ax.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/az.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ba.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/bb.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/bd.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/be.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/bf.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/bg.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/bh.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/bi.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/bj.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/bl.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/bm.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/bn.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/bo.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/bq.svg', package: 'country_icons'),
          // SvgPicture.asset('icons/flags/svg/br.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/bs.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/bt.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/bv.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/bw.svg', package: 'country_icons'),
          // SvgPicture.asset('icons/flags/svg/by.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/bz.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ca.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/cc.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/cd.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/cf.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/cg.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ch.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ci.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ck.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/cl.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/cm.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/cn.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/co.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/cr.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/cu.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/cv.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/cw.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/cx.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/cy.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/cz.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/de.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/dj.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/dk.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/dm.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/do.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/dz.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ec.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ee.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/eg.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/eh.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/er.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/es.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/et.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/eu.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/fi.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/fj.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/fk.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/fm.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/fo.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/fr.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ga.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/gb-eng.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/gb-nir.svg', package: 'country_icons'),
          // SvgPicture.asset('icons/flags/svg/gb-sct.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/gb-wls.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/gb.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/gd.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ge.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/gf.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/gg.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/gh.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/gi.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/gl.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/gm.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/gn.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/gp.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/gq.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/gr.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/gs.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/gt.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/gu.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/gw.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/gy.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/hk.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/hm.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/hn.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/hr.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ht.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/hu.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/id.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ie.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/il.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/im.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/in.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/io.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/iq.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ir.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/is.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/it.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/je.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/jm.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/jo.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/jp.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ke.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/kg.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/kh.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ki.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/km.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/kn.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/kp.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/kr.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/kw.svg', package: 'country_icons'),
          // SvgPicture.asset('icons/flags/svg/ky.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/kz.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/la.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/lb.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/lc.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/li.svg', package: 'country_icons'),
          // SvgPicture.asset('icons/flags/svg/lk.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/lr.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ls.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/lt.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/lu.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/lv.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ly.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ma.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/mc.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/md.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/me.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/mf.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/mg.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/mh.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/mk.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ml.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/mm.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/mn.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/mo.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/mp.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/mq.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/mr.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ms.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/mt.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/mu.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/mv.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/mw.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/mx.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/my.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/mz.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/na.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/nc.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ne.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/nf.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ng.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ni.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/nl.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/no.svg', package: 'country_icons'),
          // SvgPicture.asset('icons/flags/svg/np.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/nr.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/nu.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/nz.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/om.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/pa.svg', package: 'country_icons'),
          // SvgPicture.asset('icons/flags/svg/pe.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/pf.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/pg.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ph.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/pk.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/pl.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/pm.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/pn.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/pr.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ps.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/pt.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/pw.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/py.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/qa.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/re.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ro.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/rs.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ru.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/rw.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/sa.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/sb.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/sc.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/sd.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/se.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/sg.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/sh.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/si.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/sj.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/sk.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/sl.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/sm.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/sn.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/so.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/sr.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ss.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/st.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/sv.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/sx.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/sy.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/sz.svg', package: 'country_icons'),
          // SvgPicture.asset('icons/flags/svg/tc.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/td.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/tf.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/tg.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/th.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/tj.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/tk.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/tl.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/tm.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/tn.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/to.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/tr.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/tt.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/tv.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/tw.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/tz.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ua.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ug.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/um.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/us.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/uy.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/uz.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/va.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/vc.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ve.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/vg.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/vi.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/vn.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/vu.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/wf.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ws.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/xk.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/ye.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/yt.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/za.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/zm.svg', package: 'country_icons'),
          SvgPicture.asset('icons/flags/svg/zw.svg', package: 'country_icons'),
        ],
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
